apiVersion: v1
kind: Namespace
metadata:
  name: samm-maturity
  labels:
    app.kubernetes.io/name: samm-maturity-platform
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
