name: Security Scanner

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  security-scan:
    uses: 77Negativo/core-action-sec/.github/workflows/simples-scan.yml@main
    permissions:
      contents: read
      checks: write
      pull-requests: write
    secrets: inherit
